### ISSUE TITLE
omniSD format

### ISSUE THREAD

**Issue by strukturart** [canyouswim/Caching-on-Kai#12]
thank you for sharing your app with us
https://gitlab.com/banana-hackers/store-db/-/commit/25211d35d0fd2296161005d37f4c622808c9b9d8

If it were possible that you offer the app in omniSD format, that would make the installation with bHackerStore client possible
https://wiki.bananahackers.net/development/your-first-app

thank you

**Comment by jm42** [comment]
Meanwhile, here it is: [catching-on-kai.zip](https://github.com/canyouswim/Caching-on-Kai/files/5478668/catching-on-kai.zip) (364K).

**Comment by canyouswim** [comment]
thank you jm42!  i'll get that submitted

**Comment by canyouswim** [comment]
updated!  restructured directory layout to include a build folder and updated the omniSD build file w/ latest code as of tonight.  submitted merge request to the store

**Comment by strukturart** [comment]
something is wrong in the metadata

**Comment by jm42** [comment]
> include a build folder

Including the build/binaries in the git repository is not well regarded, git is made for plain files. Better would be to create releases and upload the build in them.

**Comment by canyouswim** [comment]
ah - thanks.  my git foo is not yet fully formed.  i'll do this.  i'll also check out the metadata

**Comment by canyouswim** [comment]
hopefully 3rd time is the charm for the omniSD format - realized the appID was incorrect and not set in the app's manifest document - added that, fingers crossed now.  also restructured the git structure to move build binaries out to releases

**Comment by strukturart** [comment]
there is still a problem with the metadata.json file the version number should be an integer e.g .: "version": 1

**Comment by canyouswim** [comment]
dang - so close.  fixing.

**Comment by canyouswim** [comment]
ok - i've updated the metadata.json file to be "version": 1, updated the zip, and re-uploaded to the release.  hopefully it works now....

**Comment by jm42** [comment]
Works!

**Comment by canyouswim** [comment]
/wipes brow/ alrighty then!  i guess fourth time was the charm :)
