### ISSUE TITLE
Exit the app with Back

### ISSUE THREAD

**Issue by jm42** [canyouswim/Caching-on-Kai#14]
No matter how many times I press _Back_, it won't exit the application.

Remember that some phones (ex. Nokia 8110 4G) don't have _EndCall_ button **and** _Back_. Just the later.

Here is some [button behavior](http://ukaiosdev.wikidot.com/device#toc0) explanation.

**Comment by canyouswim** [comment]
Thanks!  i'll check into this - i actually have a 8110, but didn't think to test with it.  i'll get on that.

**Comment by canyouswim** [comment]
ok - updated code now will quit when hitting back/end from the map screen

**Comment by david-p-s** [comment]
¿Can you add a "exit" button with window.close() at the option menu?

**Comment by canyouswim** [comment]
yep, will do today

**Comment by canyouswim** [comment]
a Quit option has been added to the Option menu now - you can pull the latest version here - https://github.com/canyouswim/Caching-on-Kai/releases/download/v1.0.2/caching-on-kai.zip

i'm working to get this correctly working for omniSD in the appstore now
