### ISSUE TITLE
v1.2.0 review

### ISSUE THREAD

**Issue by david-p-s** [canyouswim/Caching-on-Kai#20]
- [ ] The "Refresh-caches-where-I-want-on-the-map" feature is working well. 

It's a very good feature! I love it. I tried it loading caches far away from home, set wifi and data off, and go there without closing Caching-on-kai. It works prety nice in this "offline mode". But it loads 50+50+...+50 caches at the array everytime you push the button. Maybe it can break the memory if you load too many times? If not, is welldone like that.

- [ ] I can't see this button on my screen, so i can't change units:

			<button class="navItem" tabIndex="90" data-function="toggleUnits"><div id="unitsDisplay"></div>

- [ ] This is a minor thing... Names of the buttons.

I also think that changing the name of the menu items to these others can simplify the way of handling the app because it would help to remember the shortcuts. Something like this, with the number there to remember it:

`
①- ZOOM+③
② Center on goal geocache
ENTER: Center on my position
✆ Caché details.
(#) is free

		<div class="view" id="viewOptions">
			<button class="navItem" tabIndex="0" data-function="viewLogs"><div id="viewLogsText">④ View Cache Logs</div></button>
			<button class="navItem" tabIndex="10" data-function="viewGallery"><div id="viewGalleryText">⑤ View Cache Gallery</div></button>	
			<button class="navItem" tabIndex="20" data-function="LogCache"><div id="logCacheText">⑥ Log Cache</div></button>
			<button class="navItem" tabIndex="30" data-function="refreshList">⑦ Refresh Cache List</button>	

			<button class="navItem" tabIndex="40" data-function="viewAllCaches"><div id="cacheIconDisplay">⑧ Toggle caches on Map</div></button>	
			<button class="navItem" tabIndex="50" data-function="viewCompass">⑨ View Compass</button>
			<button class="navItem" tabIndex="60" data-function="toggleUnits"><div id="unitsDisplay">(*) Change Units</div>	

			<button class="navItem" tabIndex="70" data-function="HelpAndAbout">Ⓞ About"></button>	
			<button class="navItem" tabIndex="80" data-function="quit">🔚 Quit</button>
</button>				
		</div>	

`

- [ ] The "Quit" button is nice, I always use it. Back button works well. But, on the other hand,  I think use 🔚 for "goback" is better than for "close", but is only my opinion.

- [ ] And other issue can be this: I'm always navigating to the Null Island... https://en.wikipedia.org/wiki/Null_Island

Maybe would it be nice set home location to iniciate the first position if gps is off. So you don't need to turn it on just for search what's new arrown you. Then you can store and use last position if you are seeking and the signal is missing or you turn off the gps. Home location can be get from here: https://www.geocaching.com/account/settings/homelocation

Also do something similar to the coordinates of de goal cache, so if you select anything, it redirects you to your position when center the map. 

- [ ] I love this app

**Comment by canyouswim** [comment]
awesome comments!  i love the feedback - this is _very_ much appreciated and exactly how i had hoped going live with the app would turn out :) .  I'm going to open all these as issues so we can continue the conversation on them.  Keep it up!

**Comment by canyouswim** [comment]
what phone do you use, btw?

**Comment by david-p-s** [comment]
Nokia 8110 4g (banana phone)

**Comment by canyouswim** [comment]
Happy weekend!  i invited you as a collaborator to the repo, if you would like to directly contribute to the app - no pressure and not required, but you have good insight and skills

**Comment by david-p-s** [comment]
I'll look. But it's my first time using github. I hope I don't break anything.

**Comment by canyouswim** [comment]
it's up to you, honestly.  i'm totally happy to keep taking feedback - going collaborator is only if you feel comfortable and "called" to do so :)  this project was my first time using github as well.  there is a desktop app which helps manage creating a branch to work on and then submitting the branch back for review and merging into the master branch of the code, which i can handle.

**Comment by david-p-s** [comment]
I have got the Git program installed at all my computers. Now I'm learning
to use it. Give me a few days :-)

I have just cloned the project and I have installed it on my phone. The
"toggle units button" now works fine. Maybe I didn't have the good version
the other day?

What can I work in to try to learn how to commit? Can I write a "give me
coordinates" function?

**Comment by canyouswim** [comment]
yes to the give me coordinates function!  create an issue for that, like you did for the logo (which is awesome), and have at - you could bundle that new function into the new logo work i was recommending you take a stab at as well if you'd like?
