### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by david-p-s** [canyouswim/Caching-on-Kai#28]
https://www.geocaching.com/about/logousage.aspx

What do you think about using an original logo in order to avoid legal isues in the future? 

Do you like something like this?
![caching-on-kai_icon112x112](https://user-images.githubusercontent.com/68908215/98464171-50076a00-21c1-11eb-9df1-ed35edc2a1c4.png)

This can be the full name:
![caching-on-kai_FullName](https://user-images.githubusercontent.com/68908215/98465137-77f9cc00-21c7-11eb-896b-165e728d8e9c.png)

**Comment by canyouswim** [comment]
ooh - i love it!  and this can be a good first branch/commit/pull request to play with :)  

So, steps to work with on your side:
- Create a new branch for your work, and pull this down on your computer (your desktop Git manager can do these actions)
- then the code files on your machine will be versioned under that branch, including any files within folders - go ahead and drop 56px and 112px versions of the logo to /assets/icons
- update the manifest & index.html files to reference the new icons
- commit your changes/branch back to the repository (this just copies your changes back to Git)
- when you're ready, create a pull request (your Git desktop app can do this function as well)
- then i can review the pull request, and if all is cool, will merge to master and it's live!

**Comment by david-p-s** [comment]
I think that I commited in the main branch... sorry. I think that I didn't create a new branch. 

I hope it works.

**Comment by canyouswim** [comment]
no worries!  the commits are all clean and look great - thanks for the work :)  do you know how to create a new branch?  i've forgotten to create a new branch before when working from my desktop - if you've already done some local work on the master branch, when you create a new branch from the Git desktop app, it should ask you if you want to move your updates over to the new branch, so all is not lost... let me know if you want some pointers there?

**Comment by canyouswim** [comment]
i've tweaked the Git config to force a new branch to be created if we accidentally try to commit directly to master, which should help our workflows going forward :)
