### ISSUE TITLE
yml file on b-hackers store db

### ISSUE THREAD

**Issue by david-p-s** [canyouswim/Caching-on-Kai#35]
https://gitlab.com/banana-hackers/store-db/-/blob/master/apps/kaicaching.yml

I find that this links always refers to the last release, maybe is better than go changing every time. 
https://github.com/canyouswim/caching-on-kai/releases/latest/download/caching-on-kai.zip

This link is missing:
https://raw.githubusercontent.com/canyouswim/Caching-on-Kai/master/application/assets/icons/icons8-geocaching-112.png

**Comment by canyouswim** [comment]
ha - i beat you to it on the persistent download link - i've already made that request and submitted for update.  i will get the icon updated though, especially now that we have a new awesome one!

**Comment by canyouswim** [comment]
the persistent link is now live, and the merge request has been submitted for the broken logo image
